[2025-07-25T11:15:06.283+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T11:15:06.294+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-25T11:15:06.302+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-25T11:15:06.302+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-25T11:15:06.315+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-17 00:00:00+00:00
[2025-07-25T11:15:06.323+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmputvff75m']
[2025-07-25T11:15:06.325+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask extract_task.crawl_news
[2025-07-25T11:15:06.327+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3424) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T11:15:06.328+0000] {standard_task_runner.py:72} INFO - Started process 3434 to run task
[2025-07-25T11:15:06.360+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [running]> on host 74cfddf97016
[2025-07-25T11:15:06.421+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-17T00:00:00+00:00'
[2025-07-25T11:15:06.421+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-25T11:15:06.434+0000] {logging_mixin.py:190} INFO - Get news from 20250717T0000 to 20250717T2359
[2025-07-25T11:15:08.402+0000] {logging_mixin.py:190} INFO - Get news from 20250717T0000 to 20250717T1200
[2025-07-25T11:15:10.224+0000] {logging_mixin.py:190} INFO - Get news from 20250717T1201 to 20250717T2359
[2025-07-25T11:15:11.004+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:15:11.023+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-17T00:00:00+00:00, execution_date=20250717T000000, start_date=20250725T111506, end_date=20250725T111511
[2025-07-25T11:15:11.041+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-25T11:15:11.042+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 112 for task extract_task.crawl_news ('\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'; 3434)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:15:11.081+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-25T11:15:11.096+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T11:15:11.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-25T11:54:14.832+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T11:54:14.856+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-25T11:54:14.873+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-25T11:54:14.873+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-25T11:54:14.894+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-17 00:00:00+00:00
[2025-07-25T11:54:14.906+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmpc2d0hvgq']
[2025-07-25T11:54:14.910+0000] {standard_task_runner.py:105} INFO - Job 175: Subtask extract_task.crawl_news
[2025-07-25T11:54:14.912+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5008) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T11:54:14.913+0000] {standard_task_runner.py:72} INFO - Started process 5018 to run task
[2025-07-25T11:54:14.987+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [running]> on host 74cfddf97016
[2025-07-25T11:54:15.144+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-17T00:00:00+00:00'
[2025-07-25T11:54:15.145+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-25T11:54:15.180+0000] {logging_mixin.py:190} INFO - Get news from 20250717T0000 to 20250717T2359
[2025-07-25T11:54:15.994+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:54:16.011+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-17T00:00:00+00:00, execution_date=20250717T000000, start_date=20250725T115414, end_date=20250725T115416
[2025-07-25T11:54:16.042+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-25T11:54:16.043+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 175 for task extract_task.crawl_news ('\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'; 5018)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:54:16.097+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-25T11:54:16.125+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T11:54:16.139+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-26T05:03:05.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T05:03:05.456+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-26T05:03:05.467+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-26T05:03:05.468+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-26T05:03:05.491+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-17 00:00:00+00:00
[2025-07-26T05:03:05.501+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmp3jchnwgo']
[2025-07-26T05:03:05.505+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask extract_task.crawl_news
[2025-07-26T05:03:05.507+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2741) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T05:03:05.508+0000] {standard_task_runner.py:72} INFO - Started process 2751 to run task
[2025-07-26T05:03:05.546+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-17T00:00:00+00:00 [running]> on host 3bc71adbf7e0
[2025-07-26T05:03:05.689+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-17T00:00:00+00:00'
[2025-07-26T05:03:05.692+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-26T05:03:05.720+0000] {logging_mixin.py:190} INFO - Get news from 20250717T0000 to 20250717T2359
[2025-07-26T05:03:08.850+0000] {logging_mixin.py:190} INFO - Get news from 20250717T0000 to 20250717T1200
[2025-07-26T05:03:11.151+0000] {logging_mixin.py:190} INFO - Get news from 20250717T1201 to 20250717T2359
[2025-07-26T05:03:14.421+0000] {logging_mixin.py:190} INFO - The process of crawling 2367 news was successful
[2025-07-26T05:03:14.422+0000] {logging_mixin.py:190} INFO - Saving at /opt/airflow/data/raw/news/crawl_news-20250717.json
[2025-07-26T05:03:14.424+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T05:03:14.428+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-26T05:03:14.429+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-17T00:00:00+00:00, execution_date=20250717T000000, start_date=20250726T050305, end_date=20250726T050314
[2025-07-26T05:03:14.468+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T05:03:14.482+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T05:03:14.487+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
