[2025-07-25T11:15:59.698+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T11:15:59.711+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-25T11:15:59.719+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-25T11:15:59.720+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-25T11:15:59.732+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-18 00:00:00+00:00
[2025-07-25T11:15:59.739+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-18T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmpu8pj313f']
[2025-07-25T11:15:59.741+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask extract_task.crawl_news
[2025-07-25T11:15:59.743+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3611) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T11:15:59.744+0000] {standard_task_runner.py:72} INFO - Started process 3621 to run task
[2025-07-25T11:15:59.780+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [running]> on host 74cfddf97016
[2025-07-25T11:15:59.839+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T00:00:00+00:00'
[2025-07-25T11:15:59.840+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-25T11:15:59.854+0000] {logging_mixin.py:190} INFO - Get news from 20250718T0000 to 20250718T2359
[2025-07-25T11:16:00.689+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:16:00.697+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-18T00:00:00+00:00, execution_date=20250718T000000, start_date=20250725T111559, end_date=20250725T111600
[2025-07-25T11:16:00.714+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-25T11:16:00.715+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 119 for task extract_task.crawl_news ('\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'; 3621)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:16:00.762+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-25T11:16:00.776+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T11:16:00.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-25T11:55:01.978+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T11:55:02.018+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-25T11:55:02.056+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-25T11:55:02.060+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-25T11:55:02.098+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-18 00:00:00+00:00
[2025-07-25T11:55:02.119+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-18T00:00:00+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmpxzykil7t']
[2025-07-25T11:55:02.124+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask extract_task.crawl_news
[2025-07-25T11:55:02.130+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5117) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T11:55:02.131+0000] {standard_task_runner.py:72} INFO - Started process 5127 to run task
[2025-07-25T11:55:02.183+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [running]> on host 74cfddf97016
[2025-07-25T11:55:02.283+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T00:00:00+00:00'
[2025-07-25T11:55:02.284+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-25T11:55:02.307+0000] {logging_mixin.py:190} INFO - Get news from 20250718T0000 to 20250718T2359
[2025-07-25T11:55:03.099+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:55:03.117+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-18T00:00:00+00:00, execution_date=20250718T000000, start_date=20250725T115502, end_date=20250725T115503
[2025-07-25T11:55:03.153+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-25T11:55:03.154+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 181 for task extract_task.crawl_news ('\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'; 5127)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:55:03.195+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-25T11:55:03.244+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T11:55:03.259+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-26T05:08:45.914+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T05:08:45.935+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-26T05:08:45.945+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-26T05:08:45.946+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-26T05:08:45.962+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-18 00:00:00+00:00
[2025-07-26T05:08:45.970+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-18T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmps6u797cf']
[2025-07-26T05:08:45.972+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask extract_task.crawl_news
[2025-07-26T05:08:45.975+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5732) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T05:08:45.976+0000] {standard_task_runner.py:72} INFO - Started process 5742 to run task
[2025-07-26T05:08:46.010+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-18T00:00:00+00:00 [running]> on host 3bc71adbf7e0
[2025-07-26T05:08:46.087+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T00:00:00+00:00'
[2025-07-26T05:08:46.088+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-26T05:08:46.102+0000] {logging_mixin.py:190} INFO - Get news from 20250718T0000 to 20250718T2359
[2025-07-26T05:08:49.436+0000] {logging_mixin.py:190} INFO - The process of crawling 988 news was successful
[2025-07-26T05:08:49.437+0000] {logging_mixin.py:190} INFO - Saving at /opt/airflow/data/raw/news/crawl_news-20250718.json
[2025-07-26T05:08:49.440+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T05:08:49.446+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-26T05:08:49.446+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-18T00:00:00+00:00, execution_date=20250718T000000, start_date=20250726T050845, end_date=20250726T050849
[2025-07-26T05:08:49.486+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T05:08:49.505+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T05:08:49.510+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
