[2025-07-25T11:17:11.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T11:17:11.421+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-25T11:17:11.430+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-25T11:17:11.430+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-25T11:17:11.445+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-19 00:00:00+00:00
[2025-07-25T11:17:11.453+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-19T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmpt70xxlqn']
[2025-07-25T11:17:11.455+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask extract_task.crawl_news
[2025-07-25T11:17:11.457+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3979) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T11:17:11.458+0000] {standard_task_runner.py:72} INFO - Started process 3989 to run task
[2025-07-25T11:17:11.509+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [running]> on host 74cfddf97016
[2025-07-25T11:17:11.860+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T00:00:00+00:00'
[2025-07-25T11:17:11.861+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-25T11:17:11.897+0000] {logging_mixin.py:190} INFO - Get news from 20250719T0000 to 20250719T2359
[2025-07-25T11:17:12.281+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:17:12.294+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-19T00:00:00+00:00, execution_date=20250719T000000, start_date=20250725T111711, end_date=20250725T111712
[2025-07-25T11:17:12.317+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-25T11:17:12.318+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 130 for task extract_task.crawl_news ('\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'; 3989)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:17:12.357+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-25T11:17:12.376+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T11:17:12.385+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-25T11:55:53.301+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T11:55:53.315+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-25T11:55:53.324+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-25T11:55:53.324+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-25T11:55:53.339+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-19 00:00:00+00:00
[2025-07-25T11:55:53.348+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-19T00:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmps2w7zw70']
[2025-07-25T11:55:53.350+0000] {standard_task_runner.py:105} INFO - Job 187: Subtask extract_task.crawl_news
[2025-07-25T11:55:53.354+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5224) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T11:55:53.355+0000] {standard_task_runner.py:72} INFO - Started process 5234 to run task
[2025-07-25T11:55:53.390+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [running]> on host 74cfddf97016
[2025-07-25T11:55:53.462+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T00:00:00+00:00'
[2025-07-25T11:55:53.463+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-25T11:55:53.478+0000] {logging_mixin.py:190} INFO - Get news from 20250719T0000 to 20250719T2359
[2025-07-25T11:55:54.329+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:55:54.340+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-19T00:00:00+00:00, execution_date=20250719T000000, start_date=20250725T115553, end_date=20250725T115554
[2025-07-25T11:55:54.360+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-25T11:55:54.361+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 187 for task extract_task.crawl_news ('\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'; 5234)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/elt_to_dwh/extract/crawl_news.py", line 40, in crawl_news
    raise KeyError(f"'feed' key not found in response. Full response:\n{json.dumps(response, indent=4)}")
KeyError: '\'feed\' key not found in response. Full response:\n{\n    "Information": "We have detected your API key as RSKHO6B8SELFWUYG and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."\n}'
[2025-07-25T11:55:54.373+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-25T11:55:54.388+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T11:55:54.394+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-26T05:09:26.282+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T05:09:26.294+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-26T05:09:26.301+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [queued]>
[2025-07-26T05:09:26.301+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-26T05:09:26.315+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task.crawl_news> on 2025-07-19 00:00:00+00:00
[2025-07-26T05:09:26.322+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'elt_to_dwh', 'extract_task.crawl_news', 'scheduled__2025-07-19T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/elt_to_dwh.py', '--cfg-path', '/tmp/tmp1xeayk3u']
[2025-07-26T05:09:26.323+0000] {standard_task_runner.py:105} INFO - Job 96: Subtask extract_task.crawl_news
[2025-07-26T05:09:26.325+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5858) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T05:09:26.326+0000] {standard_task_runner.py:72} INFO - Started process 5868 to run task
[2025-07-26T05:09:26.355+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_to_dwh.extract_task.crawl_news scheduled__2025-07-19T00:00:00+00:00 [running]> on host 3bc71adbf7e0
[2025-07-26T05:09:26.417+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='elt_to_dwh' AIRFLOW_CTX_TASK_ID='extract_task.crawl_news' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T00:00:00+00:00'
[2025-07-26T05:09:26.418+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-26T05:09:26.429+0000] {logging_mixin.py:190} INFO - Get news from 20250719T0000 to 20250719T2359
[2025-07-26T05:09:28.311+0000] {logging_mixin.py:190} INFO - The process of crawling 199 news was successful
[2025-07-26T05:09:28.311+0000] {logging_mixin.py:190} INFO - Saving at /opt/airflow/data/raw/news/crawl_news-20250719.json
[2025-07-26T05:09:28.313+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T05:09:28.318+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-26T05:09:28.319+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=elt_to_dwh, task_id=extract_task.crawl_news, run_id=scheduled__2025-07-19T00:00:00+00:00, execution_date=20250719T000000, start_date=20250726T050926, end_date=20250726T050928
[2025-07-26T05:09:28.350+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T05:09:28.373+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T05:09:28.379+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
